language: go
go:
- 1.x
- 1.11.x
install:
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls
script:
- make
- go test -v -covermode=count -coverprofile=coverage.out
- "$HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN"
env:
  global:
  - GO111MODULE=on
  - secure: eXADsETNPK2nXF2eI8Ap2p4w8b/GlM/LRpfeIpy/ZKva9ZDrxAV0HBI7lD6xkfhwjZuZBIVq7yl6B5Qxzd3JyJXisYJXpplF0ZN86KxCYYpnQrni7krj0DampD2EE2YociI+itwDfME8j2V9O+dNrWHHNAX0XXD1i/iXsm8t8N8iNDyTgrGyhp3oE8f7YgBa8oEKuExRCXplYGieJeeBxTeWdXXn8/ddP5JOvlfqmXoNNQwH47n58DK0aTFqJSnFKLVtpvrDzO04lNUfjHYuJXwfa1sSl8r96Lt58uWvYoEqT0he6hrS8GDEAAS6qj06kCBhQEo9AGRRJlq40BpDCbMBsrXaxWGxSM9fJj1AXhf8am1Eb3Zukd9HvH9glJId6KnbNIPSgBaVl65t9RrLNI6XXYJVUxVCoW9Tg46q2eZNU7m4b8GR90M//zkaizBIchOgSUZrRTdMLXxglvwJ5gN96LWg68E7drjgtkAVsfZTqeFOYw1LzUM1mUHCen50ctsXPBvwfJrFVMpCJaczsX8cie805r7ecSe5ogNEELMqYDKrcl7y7rgs/NxGN7wPWAhv+x/3elK7zTwYG+b+De/sn35zw1xaTiqn9b9/FWXtdMfX5qzZ90uEvBb1Jucjwq9qoIz5ocGdkD2qaZDNcxN2FzvRf3RP6hYKc25xq1A=
